apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 71-worker-motd
spec:
  config:
    ignition:
      version: 3.4.0
  storage:
    files:
      - path: /etc/motd
        mode: 0444
        filesystem: root
        overwrite: true
        contents:
          source: data:text/plain;charset=utf-8;base64,V2VsY29tZSB0byB0aGUgT3BlblNoaWZ0IEFkbWluaXN0cmF0aW9uIElJSQo=
