apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 72-worker-motd
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
      - path: /etc/motd
        mode: 0644
        filesystem: root
        overwrite: true
        contents:
          source: data:text/plain;base64,ClRoZSBwcm9ncmFtcyBpbmNsdWRlZCB3aXRoIHRoZSBLYWxpIEdOVS9MaW51eCBzeXN0ZW0gYXJlIGZyZWUgc29mdHdhcmU7CnRoZSBleGFjdCBkaXN0cmlidXRpb24gdGVybXMgZm9yIGVhY2ggcHJvZ3JhbSBhcmUgZGVzY3JpYmVkIGluIHRoZQppbmRpdmlkdWFsIGZpbGVzIGluIC91c3Ivc2hhcmUvZG9jLyovY29weXJpZ2h0LgoKS2FsaSBHTlUvTGludXggY29tZXMgd2l0aCBBQlNPTFVURUxZIE5PIFdBUlJBTlRZLCB0byB0aGUgZXh0ZW50CnBlcm1pdHRlZCBieSBhcHBsaWNhYmxlIGxhdy4K
